# pytest.ini
[pytest]
# Cambiamos el modo a 'auto' para que descubra fixtures y tests async automáticamente
asyncio_mode = auto
asyncio_default_test_loop_scope = function

# Opcional: Silenciar advertencias de librerías de terceros (como multipart)
filterwarnings =
    ignore::PendingDeprecationWarning
    ignore::DeprecationWarning