"""Sprint 1 Módulo 2 - Creacion inicial sgf_core

Revision ID: 669d36bf6e99
Revises: 
Create Date: 2026-05-22 17:07:26.911956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '669d36bf6e99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('imei_hash', sa.String(length=255), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispositivos_imei_hash'), 'dispositivos', ['imei_hash'], unique=True)
    op.create_geospatial_table('registros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispositivo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', postgresql.ENUM('VEHICULO', 'COMERCIO', 'ACTIVIDAD', name='tipo_acta_enum'), nullable=False),
    sa.Column('estado', postgresql.ENUM('EMITIDA', 'ANULADA', 'OBSERVADA', name='estado_acta_enum'), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_recepcion_server', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_registros_ubicacion', 'registros', ['ubicacion'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('auditoria_eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registro_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fecha_evento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operador_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['registro_id'], ['registros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_eventos_registro_id'), 'auditoria_eventos', ['registro_id'], unique=False)
    op.add_column('vehiculos', sa.Column('marca_modelo', sa.String(length=100), nullable=True))
    op.alter_column('vehiculos', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vehiculos', 'patente',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index('idx_vehiculos_patente', table_name='vehiculos')
    op.create_index(op.f('ix_vehiculos_patente'), 'vehiculos', ['patente'], unique=False)
    op.create_foreign_key(None, 'vehiculos', 'registros', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('vehiculos', 'modelo')
    op.drop_column('vehiculos', 'marca')
    op.drop_column('vehiculos', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('vehiculos', sa.Column('marca', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('vehiculos', sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehiculos', type_='foreignkey')
    op.drop_index(op.f('ix_vehiculos_patente'), table_name='vehiculos')
    op.create_index('idx_vehiculos_patente', 'vehiculos', ['patente'], unique=False)
    op.alter_column('vehiculos', 'patente',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('vehiculos', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('vehiculos', 'marca_modelo')
    op.drop_index(op.f('ix_auditoria_eventos_registro_id'), table_name='auditoria_eventos')
    op.drop_table('auditoria_eventos')
    op.drop_geospatial_index('idx_registros_ubicacion', table_name='registros', postgresql_using='gist', column_name='ubicacion')
    op.drop_geospatial_table('registros')
    op.drop_index(op.f('ix_dispositivos_imei_hash'), table_name='dispositivos')
    op.drop_table('dispositivos')
    # ### end Alembic commands ###
