"""Agrega tabla Evidencias

Revision ID: fcdac7bd50b0
Revises: 669d36bf6e99
Create Date: 2026-05-25 10:55:49.934105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcdac7bd50b0'
down_revision: Union[str, None] = '669d36bf6e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('acta_id', sa.UUID(), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('peso_bytes', sa.Integer(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acta_id'], ['registros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_acta_id'), 'evidencias', ['acta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidencias_acta_id'), table_name='evidencias')
    op.drop_table('evidencias')
    # ### end Alembic commands ###
